### ISSUE TITLE
lateinit property application has not been initialized

### ISSUE THREAD

**Issue by g19980115** [vincent-series/smart-show#58]
```
lateinit property application has not been initialized

解析原始

java.lang.ExceptionInInitializerError:
com.coder.vincent.smart_toast.ConstantsKt.int getDEFAULT_TOAST_Y_OFFSET()(ConstantsKt.java:14)
......
অ:lateinit property application has not been initialized
com.coder.vincent.series.common_lib.ToolkitKt.void setApplication(android.app.Application)(ToolkitKt.java:25)
com.coder.vincent.series.common_lib.ToolkitKt.android.app.Application getApplication()(ToolkitKt.java:25)
com.coder.vincent.smart_toast.ConstantsKt.void <clinit>()(ConstantsKt.java:14)
com.coder.vincent.smart_toast.ConstantsKt.int getDEFAULT_TOAST_Y_OFFSET()(ConstantsKt.java:14)
com.coder.vincent.smart_toast.alias.classic.ClassicToastInvoker.void show(java.lang.CharSequence)(ClassicToastInvoker.java:27)
```

版本：`implementation "io.github.vincent-series:smart-toast:4.0.3"`

线上收到的崩溃日志。
在BroadcastReceiver中使用的

**Comment by vincent-series** [comment]
@g19980115 请问广播接收器接受的是静态广播么？

**Comment by g19980115** [comment]
是的

**Comment by vincent-series** [comment]
> 是的

你监听的是什么静态广播，我这边想模拟一下？是系统广播么？方便加个微信进行交流么

**Comment by g19980115** [comment]
是一个安装成功的广播，`android.intent.action.PACKAGE_REPLACED`，线上的，我这边也没办法复现，是否可以提供一个手动设置context的接口

**Comment by vincent-series** [comment]
> 是一个安装成功的广播，`android.intent.action.PACKAGE_REPLACED`，线上的，我这边也没办法复现，是否可以提供一个手动设置context的接口
你好，现在已支持手动强制初始化。可以在你的Receiver里，调用如下代码：
        VincentSeriesLib.initialize(application)

然后再调用显示toast

**Comment by g19980115** [comment]
> > 是一个安装成功的广播，`android.intent.action.PACKAGE_REPLACED`，线上的，我这边也没办法复现，是否可以提供一个手动设置context的接口
> > 你好，现在已支持手动强制初始化。可以在你的Receiver里，调用如下代码：
> > VincentSeriesLib.initialize(application)
> 
> 然后再调用显示toast

谢谢
