### ISSUE TITLE
backgroundResource(R.drawable.toast_bg)

### ISSUE THREAD

**Issue by crazecoder** [vincent-series/smart-show#65]
android:layout_gravity="center_horizontal"

既然可以自定义背景drawable了，为什么textview的layout_gravity不设成center，drawable如果设置size，就不居中了。。。
```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle">
            <padding
                android:bottom="2px"
                android:left="2px"
                android:right="2px"
                android:top="2px" />
            <solid android:color="#0DCCCCCC" />
            <corners android:radius="20dp" />
        </shape>
    </item>
    <item>
        <shape android:shape="rectangle">
            <padding
                android:bottom="2px"
                android:left="2px"
                android:right="2px"
                android:top="2px" />
            <solid android:color="#10CCCCCC" />
            <corners android:radius="20dp" />
        </shape>
    </item>
    <item>
        <shape android:shape="rectangle">
            <padding
                android:bottom="2px"
                android:left="2px"
                android:right="2px"
                android:top="2px" />
            <solid android:color="#15CCCCCC" />
            <corners android:radius="20dp" />
        </shape>
    </item>
    <item>
        <shape android:shape="rectangle">
            <padding
                android:bottom="2px"
                android:left="2px"
                android:right="2px"
                android:top="2px" />
            <solid android:color="#20CCCCCC" />
            <corners android:radius="20dp" />
        </shape>
    </item>
    <item>
        <shape android:shape="rectangle">
            <padding
                android:bottom="2px"
                android:left="2px"
                android:right="2px"
                android:top="2px" />
            <solid android:color="#30CCCCCC" />
            <corners android:radius="20dp" />
        </shape>
    </item>
    <item>
        <shape android:shape="rectangle" >
            <solid android:color="#14898989" />
            <corners android:radius="20dp" />
            <padding android:bottom="2px"
                android:left="2px"
                android:right="2px"
                android:top="2px" />
        </shape>
    </item>
    <item>
        <shape android:shape="rectangle" >
            <corners android:radius="20dp" />
            <size android:height="40dp"/>
            <solid android:color="#FFFFFF" />
<!--            <stroke android:width="1dp" android:color="@color/bg_gray" />-->
            <padding
                android:bottom="3px"
                android:left="3px"
                android:right="3px"
                android:top="3px" />
        </shape>
    </item>
</layer-list>
```

**Comment by vincent-series** [comment]
> android:layout_gravity="center_horizontal"
> 
> 既然可以自定义背景drawable了，为什么textview的layout_gravity不设成center，drawable如果设置size，就不居中了。。。
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
>     <item>
>         <shape android:shape="rectangle">
>             <padding
>                 android:bottom="2px"
>                 android:left="2px"
>                 android:right="2px"
>                 android:top="2px" />
>             <solid android:color="#0DCCCCCC" />
>             <corners android:radius="20dp" />
>         </shape>
>     </item>
>     <item>
>         <shape android:shape="rectangle">
>             <padding
>                 android:bottom="2px"
>                 android:left="2px"
>                 android:right="2px"
>                 android:top="2px" />
>             <solid android:color="#10CCCCCC" />
>             <corners android:radius="20dp" />
>         </shape>
>     </item>
>     <item>
>         <shape android:shape="rectangle">
>             <padding
>                 android:bottom="2px"
>                 android:left="2px"
>                 android:right="2px"
>                 android:top="2px" />
>             <solid android:color="#15CCCCCC" />
>             <corners android:radius="20dp" />
>         </shape>
>     </item>
>     <item>
>         <shape android:shape="rectangle">
>             <padding
>                 android:bottom="2px"
>                 android:left="2px"
>                 android:right="2px"
>                 android:top="2px" />
>             <solid android:color="#20CCCCCC" />
>             <corners android:radius="20dp" />
>         </shape>
>     </item>
>     <item>
>         <shape android:shape="rectangle">
>             <padding
>                 android:bottom="2px"
>                 android:left="2px"
>                 android:right="2px"
>                 android:top="2px" />
>             <solid android:color="#30CCCCCC" />
>             <corners android:radius="20dp" />
>         </shape>
>     </item>
>     <item>
>         <shape android:shape="rectangle" >
>             <solid android:color="#14898989" />
>             <corners android:radius="20dp" />
>             <padding android:bottom="2px"
>                 android:left="2px"
>                 android:right="2px"
>                 android:top="2px" />
>         </shape>
>     </item>
>     <item>
>         <shape android:shape="rectangle" >
>             <corners android:radius="20dp" />
>             <size android:height="40dp"/>
>             <solid android:color="#FFFFFF" />
> 
>             <padding
>                 android:bottom="3px"
>                 android:left="3px"
>                 android:right="3px"
>                 android:top="3px" />
>         </shape>
>     </item>
> </layer-list>
> ```

你好，已修复，请使用最新版本，4.1.1

**Comment by crazecoder** [comment]
好像还不是这个属性的问题，依然会歪，你这个界面上的逻辑有点绕啊

**Comment by vincent-series** [comment]
> 依然会歪，建议这么改，或者删除 android:orientation="vertical"
> 
> ```
> <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
>     android:layout_width="wrap_content"
>     android:layout_height="wrap_content"
>     android:background="@drawable/vincent_series_smart_toast_default_bg">
> 
>     <TextView
>         android:id="@+id/smart_toast_message"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         android:layout_gravity="center"
>         android:layout_marginLeft="16dp"
>         android:layout_marginRight="16dp"
>         android:drawablePadding="10dp"
>         android:ellipsize="end"
>         android:gravity="center"
>         android:lineSpacingExtra="2dp"
>         android:layout_centerInParent="true"
>         android:maxLines="3"
>         android:text="I'm a Toast"
>         android:textColor="#ffffff"
>         android:textSize="14sp" />
> 
> </RelativeLayout>
> ```

你好，我发了一个临时版本，你看是否能解决你的问题，如果可以我再发正式版.
implementation "io.github.vincent-series:smart-toast:4.1.2-2-SNAPSHOT"

**Comment by crazecoder** [comment]
> io.github.vincent-series:smart-toast:4.1.2-2-SNAPSHOT

Could not find io.github.vincent-series:smart-toast:4.1.2-2-SNAPSHOT.

**Comment by vincent-series** [comment]
> 可以的，你再试试，我刚才拉了下，可以拉下来

**Comment by crazecoder** [comment]
我这边拉不下来。。。

**Comment by crazecoder** [comment]
我这边拉不下来。。。

**Comment by vincent-series** [comment]
> implementation "io.github.vincent-series:smart-toast:4.1.2-2-SNAPSHOT"

我刚发了正式版，正式版的生效时间比较长，大概半小时左右：
    implementation "io.github.vincent-series:smart-toast:4.1.2"

**Comment by crazecoder** [comment]
> > implementation "io.github.vincent-series:smart-toast:4.1.2-2-SNAPSHOT"
> 
> 我刚发了正式版，正式版的生效时间比较长，大概半小时左右： implementation "io.github.vincent-series:smart-toast:4.1.2"

可以了

**Comment by vincent-series** [comment]
@

> > > implementation "io.github.vincent-series:smart-toast:4.1.2-2-SNAPSHOT"
> > 
> > 
> > 我刚发了正式版，正式版的生效时间比较长，大概半小时左右： implementation "io.github.vincent-series:smart-toast:4.1.2"
> 
> 可以了

可以居中了么？

**Comment by crazecoder** [comment]
> @
> 
> > > > implementation "io.github.vincent-series:smart-toast:4.1.2-2-SNAPSHOT"
> > > 
> > > 
> > > 我刚发了正式版，正式版的生效时间比较长，大概半小时左右： implementation "io.github.vincent-series:smart-toast:4.1.2"
> > 
> > 
> > 可以了
> 
> 可以居中了么？

可以
