### ISSUE TITLE
smart snackbar 4.1.0在不同android版本下,提示文字大小不一致

### ISSUE THREAD

**Issue by jyh149129** [vincent-series/smart-show#68]
smart snackbar升级到最新版4.1.0后，messageSizeSp设置提示文字大小，在不同版本系统上文字大小不一致（经模拟器 android 11\12\13进行了测试）

**Comment by vincent-series** [comment]
> smart snackbar升级到最新版4.1.0后，messageSizeSp设置提示文字大小，在不同版本系统上文字大小不一致（经模拟器 android 11\12\13进行了测试）

具体是怎么设置的？是直接这样传一个固定值么？.messageSizeSp(16f)

**Comment by jyh149129** [comment]
固定值。这块有修改吗？4.0.8是正常的

**Comment by vincent-series** [comment]
> 固定值。这块有修改吗？4.0.8是正常的

已修复，使用4.1.1版本，刚发布，约半小时生效
